development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: sample_development
  pool:     5
  username: pgdev
  password: pg123
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: sample_test
  pool:     5
  username: pgdev
  password: pg123
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: sample_production
  pool:     5
  username: pgdev
  password: pg123
  template: template0